import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import PagHome from './components/pagHome/pag-home'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Diego Leonardo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PagHome></PagHome>
      </main>
      
    </>
  )
}
