
import Head from "next/head"
import Projetos from "./components/projetos/pag-projetos"

export default function Home() {
    return (
      <>
        <Head>
          <title>Projetos</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Projetos></Projetos>
        </main>
        
      </>
    )
  }
  